name: paper_elements
# prevent publishing: version: 0.0.1-dev
author: Polymer.dart Authors <web-ui-dev@dartlang.org>
description: Paper elements for Dart
dependencies:
  core_elements: '>=0.0.4-dev.1 <0.0.5'
  polymer: ">=0.11.0-dev.6 <0.12.0"
dev_dependencies:
  html5lib: ">=0.11.0 <0.12.0"
  path: ">=1.0.0 <2.0.0"
  yaml: ">=1.0.0 <2.0.0"
transformers:
- polymer:
    lint: false
