name: paper_elements
version: 0.6.1
author: Polymer.dart Authors <web-ui-dev@dartlang.org>
description: Paper elements for Dart
homepage: https://www.dartlang.org/polymer-dart/
dependencies:
  core_elements: '>=0.5.0+1 <0.7.0'
  custom_element_apigen: ">= 0.1.3 <0.2.0"
  polymer: ">=0.15.2 <0.16.0"
  web_components: ">=0.9.0 <0.11.0"
dev_dependencies:
  path: ">=1.0.0 <2.0.0"
  unittest: ">=0.11.0+2 <0.12.0"
  matcher: ">=0.10.1+1 <0.12.0"
dependency_overrides:
  custom_element_apigen:
    path: ../custom-element-apigen
  core_elements:
    path: ../core-elements
transformers:
- polymer:
    entry_points:
      - test/paper_button_a11y_test.html
      - test/paper_button_basic_test.html
      - test/paper_dropdown_basic_test.html
      - test/paper_fab_a11y_test.html
      - test/paper_fab_basic_test.html
      - test/paper_icon_button_a11y_test.html
      - test/paper_icon_button_basic_test.html
      - test/paper_input_a11y_test.html
      - test/paper_input_autogrow_test.html
      - test/paper_input_decorator_test.html
      - test/paper_ripple_position_test.html
      - test/paper_shadow_basic_test.html
    lint:
      exclude: lib/src/
    inline_stylesheets:
      lib/src/paper-shadow/paper-shadow.css: true
